# 1. Tensor

In [3]:
import torch

## 1.1 Tensor Basic

In [37]:
#Tensor의 기초적 선언
#torch.FloatTensor와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)


1.00000e-45 *
  4.2039  0.0000  4.2039
  0.0000  1.4013  0.0000
[torch.FloatTensor of size 2x3]



In [38]:
#Tesnor의 정보 확인
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


## 1.2 Tensor with charateristics

In [40]:
#0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)


 0  0  0
 0  0  0
[torch.FloatTensor of size 2x3]



In [42]:
#1로 채워진 Tensor 선언
x = torch.ones(2, 3)
print(x)


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]



In [41]:
#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)


 0.6175  0.7845  0.4927
 0.9861  0.8520  0.1074
[torch.FloatTensor of size 2x3]



In [45]:
#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)


-1.7595  2.6433 -0.1610
-0.5138 -0.3416 -0.5937
[torch.FloatTensor of size 2x3]



In [46]:
#정방행렬과 같은 Tensor 선언
x = torch.eye(2, 3)
print(x)


 1  0  0
 0  1  0
[torch.FloatTensor of size 2x3]



In [49]:
#0부터 2까지 0.5씩 증가하는 Tensor 선언
x = torch.arange(0, 2, step=0.5)
print(x)


 0.0000
 0.5000
 1.0000
 1.5000
[torch.FloatTensor of size 4]



In [51]:
#직접 값을 입력하여 선언
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)


 1  2  3
 1  2  3
[torch.FloatTensor of size 2x3]



In [58]:
#32-bit floating point
x = torch.FloatTensor(2,3)
print(x)


1.00000e-05 *
  0.0000  0.0000  0.0000
  0.0000  0.0000  4.0938
[torch.FloatTensor of size 2x3]



In [59]:
#32-bit integer (signed)
x = torch.IntTensor(2,3)
print(x)


 5.3897e+08  1.9702e+09  7.7971e+08
 1.7023e+09  5.3753e+08  1.3107e+09
[torch.IntTensor of size 2x3]



## 1.3 Tensor and Numpy

In [62]:
import numpy as np

In [69]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [70]:
#numpy를 tensor로 변환
x = torch.from_numpy(x)
print(x, type(x))


 1  2  3
 1  2  3
[torch.IntTensor of size 2x3]
 <class 'torch.IntTensor'>


In [71]:
#tensor를 numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## 1.4 Tensor Slicing

In [97]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]



In [84]:
#모든 원소 출력
x[:, :]


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]

In [85]:
#2행부터 출력
x[1:, :]


  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 2x4]

In [86]:
#2열부터 출력
x[:, 1:]


  2   3   4
  6   7   8
 10  11  12
[torch.FloatTensor of size 3x3]

In [88]:
#2행, 2열부터 3열까지 출력
x[1:, 1:3]


  6   7
 10  11
[torch.FloatTensor of size 2x2]

In [89]:
#1행 출력
x[0, :]


 1
 2
 3
 4
[torch.FloatTensor of size 4]

In [122]:
#x_cols의 첫번째 배열 중 특정 부분만 추출하기
torch.masked_select(x_cols[0], torch.ByteTensor([[0,1],[1,0],[0,1]]))


  2
  5
 10
[torch.FloatTensor of size 3]

In [102]:
#x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size=1, dim=0)
#torch.chunk(x, 3, dim=0)
print(x_rows)

(
 1  2  3  4
[torch.FloatTensor of size 1x4]
, 
 5  6  7  8
[torch.FloatTensor of size 1x4]
, 
  9  10  11  12
[torch.FloatTensor of size 1x4]
)


In [111]:
#x를 2열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size=2, dim=1)
#torch.chunk(x, 2, dim=1)
print(x_cols)

(
  1   2
  5   6
  9  10
[torch.FloatTensor of size 3x2]
, 
  3   4
  7   8
 11  12
[torch.FloatTensor of size 3x2]
)


## 1.5 Tensor Merging

In [109]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1)


    1     2     3     4     5     6     7     8     9    10    11    12
[torch.FloatTensor of size 1x12]

In [130]:
#x_cols를 쌓아올리기
x_new = torch.stack(x_cols, dim=0)
print(x_new)


(0 ,.,.) = 
   1   2
   5   6
   9  10

(1 ,.,.) = 
   3   4
   7   8
  11  12
[torch.FloatTensor of size 2x3x2]



## 1.6 Tensor Reshaping

In [179]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]



In [180]:
#4행 3열로 바꾸기
x_new.view(4,3)


  1   2   5
  6   9  10
  3   4   7
  8  11  12
[torch.FloatTensor of size 4x3]

In [181]:
#2열로 바꾸기
x_new.view(-1, 2)


  1   2
  5   6
  9  10
  3   4
  7   8
 11  12
[torch.FloatTensor of size 6x2]

In [152]:
x_new.view(2, 1, -1)


(0 ,.,.) = 
   1   2   5   6   9  10

(1 ,.,.) = 
   3   4   7   8  11  12
[torch.FloatTensor of size 2x1x6]

In [153]:
#차원이 1인 값을 축소
x_new.view(2, 1, -1).squeeze()


  1   2   5   6   9  10
  3   4   7   8  11  12
[torch.FloatTensor of size 2x6]

In [170]:
#차원을 row로 자른 후 저장
x_new.view(2, 1, -1).squeeze().unsqueeze(dim=1)


(0 ,.,.) = 
   1   2   5   6   9  10

(1 ,.,.) = 
   3   4   7   8  11  12
[torch.FloatTensor of size 2x1x6]

## 1.7 Tensor for GPU

In [72]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)


 1  2  3
 1  2  3
[torch.FloatTensor of size 2x3]



In [75]:
#cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)


 1  2  3
 1  2  3
[torch.cuda.FloatTensor of size 2x3 (GPU 0)]



In [76]:
#gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)


 1  2  3
 1  2  3
[torch.FloatTensor of size 2x3]



## 1.8 Tensor Calculation

In [191]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print(x, y)


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]
 
 1  1  1
 2  2  2
[torch.FloatTensor of size 2x3]



In [192]:
# x와 y의 합
z = torch.add(x, y)
print(z, x+y)


 2  3  4
 6  7  8
[torch.FloatTensor of size 2x3]
 
 2  3  4
 6  7  8
[torch.FloatTensor of size 2x3]



In [195]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)


-1  0  1
 2  3  4
[torch.FloatTensor of size 2x3]


  2   4   6
  8  10  12
[torch.FloatTensor of size 2x3]



In [196]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print(z, x*y)


  1   2   3
  8  10  12
[torch.FloatTensor of size 2x3]
 
  1   2   3
  8  10  12
[torch.FloatTensor of size 2x3]



In [197]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print(z, x**2)


  1   4   9
 16  25  36
[torch.FloatTensor of size 2x3]
 
  1   4   9
 16  25  36
[torch.FloatTensor of size 2x3]



In [200]:
#x의 원소에 log를 씌움
z = torch.log(x)
print(z, x.log())


 0.0000  0.6931  1.0986
 1.3863  1.6094  1.7918
[torch.FloatTensor of size 2x3]
 
 0.0000  0.6931  1.0986
 1.3863  1.6094  1.7918
[torch.FloatTensor of size 2x3]



In [201]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print(z, x.sqrt())


 1.0000  1.4142  1.7321
 2.0000  2.2361  2.4495
[torch.FloatTensor of size 2x3]
 
 1.0000  1.4142  1.7321
 2.0000  2.2361  2.4495
[torch.FloatTensor of size 2x3]



In [203]:
#x의 원소에 mod 계산
z = x % 2
print(z)


 1  0  1
 0  1  0
[torch.FloatTensor of size 2x3]



In [218]:
#x에 절댓값
x = x.abs()
print(x)


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]



## 1.9 Tensor Casting

In [4]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print(x, y)


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]
 
 1  1  1
 2  2  2
[torch.FloatTensor of size 2x3]



In [6]:
x.type(torch.DoubleTensor)


 1  2  3
 4  5  6
[torch.DoubleTensor of size 2x3]

In [7]:
x.type(torch.IntTensor)


 1  2  3
 4  5  6
[torch.IntTensor of size 2x3]

## 1.10 Tensor Statistic

In [219]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)


-1  2 -3
 4 -5  6
[torch.FloatTensor of size 2x3]



In [233]:
x.sum(), x.max(), x.min(), x.var()

(3.0, 6.0, -5.0, 17.9)

In [223]:
#행을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value


 4
 2
 6
[torch.FloatTensor of size 3]

In [232]:
#열을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value


-3 -1  2
-5  4  6
[torch.FloatTensor of size 2x3]

## 1.11 Tensor Calculation as Matrix

In [236]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print(x, y)


 1  1
 2  2
[torch.FloatTensor of size 2x2]
 
 1  2
 3  4
[torch.FloatTensor of size 2x2]



In [237]:
#x와 y의 행렬곱
torch.mm(x, y)


  4   6
  8  12
[torch.FloatTensor of size 2x2]

In [246]:
#x와 z의 행렬벡터곱
z = torch.Tensor([1, 2])
torch.mv(x, z)


 3
 6
[torch.FloatTensor of size 2]

In [244]:
#z와 z의 내적
torch.dot(z, z)

5.0

In [247]:
#x의 전치(transpose)
x.t()


 1  2
 1  2
[torch.FloatTensor of size 2x2]

In [272]:
# 텐서의 배치 행렬곱
x1 = torch.FloatTensor(3,3,2)
x2 = torch.FloatTensor(3,2,3)

torch.bmm(x1,x2).size()

torch.Size([3, 3, 3])

In [273]:
# 텐서의 전치
x1.transpose(1, 2).size()

torch.Size([3, 2, 3])

In [274]:
eigenvalue, eigenvector = torch.eig(x,eigenvectors=True)
print("eigenvalue :", eigenvalue)
print("eigenvector :", eigenvector)

eigenvalue : 
 0.0000  0.0000
 3.0000  0.0000
[torch.FloatTensor of size 2x2]

eigenvector : 
-0.7071 -0.4472
 0.7071 -0.8944
[torch.FloatTensor of size 2x2]



In [256]:
#행렬의 QR factorization
Q,R = torch.qr(x)
print("Q :", Q)
print("R :", R)

Q : 
-0.4472 -0.8944
-0.8944  0.4472
[torch.FloatTensor of size 2x2]

R : 
-2.2361 -2.2361
 0.0000  0.0000
[torch.FloatTensor of size 2x2]



In [257]:
#행렬의 SVD factorization
S,V,D = torch.svd(x)
print("S :", S)
print("V :", V)
print("D :", D)

S : 
-0.4472 -0.8944
-0.8944  0.4472
[torch.FloatTensor of size 2x2]

V : 
 3.1623e+00
 8.4294e-08
[torch.FloatTensor of size 2]

D : 
-0.7071 -0.7071
-0.7071  0.7071
[torch.FloatTensor of size 2x2]

